### ISSUE TITLE
Football Market Place

### ISSUE THREAD

**Issue by celosotomaior** [iBuildApp/hackathon#23]
### iBuildApp Network Hackathon Submission

Github Repo: 
Description: 

I want to develop a network for people to buy and sell shares of football players around the world. For example: A client goes to the website, sees Neymar listed as one of the palyers and decides to buy a small percentage thru our cryptocurrency. In case Neymar is sold, the cryptocurrency Neymar will increase. The ower of the cryptocurrency can sell it anytime in one of the exchanges.

Team Members:

**Comment by Thomastheone** [comment]
Maybe the app can also include other contracts or freelances?Like company A hire two freelance graphical designers and sign a year-long contract with them but then they don't need it for the rest of the half of the year and they can sell the contracts of freerlance desginers to other companies in order to compensate their spending on insurance and legal fees?

**Comment by celosotomaior** [comment]
Exactly! You got the main idea! It could also include freelancers. At the
moment I want to focus on people (Players, Freelancers etc), but it could
also be tangible or intangible assets (Houses, arts etc).
